"""add rocm_version to diagnostic_reports

Revision ID: 21e6b6b21ff3
Revises: f113b99acf31
Create Date: 2026-05-21 20:25:39.601254

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "21e6b6b21ff3"
down_revision: str | None = "f113b99acf31"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "diagnostic_reports",
        sa.Column("rocm_version", sa.String(length=16), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("diagnostic_reports", "rocm_version")
    # ### end Alembic commands ###
