"""Add missing foreign keys

Revision ID: a855f3a2d70d
Revises: 0001
Create Date: 2026-05-14 20:17:39.940634

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a855f3a2d70d"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cuda_compatibility_matrix")
    op.alter_column(
        "ai_audit_log",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("idx_audit_safety"), table_name="ai_audit_log")
    op.drop_index(op.f("idx_audit_session"), table_name="ai_audit_log")
    op.drop_constraint(
        op.f("ai_audit_log_session_id_fkey"), "ai_audit_log", type_="foreignkey"
    )
    op.alter_column(
        "ai_sessions",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "ai_suggestions",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_constraint(
        op.f("ai_suggestions_session_id_fkey"), "ai_suggestions", type_="foreignkey"
    )
    op.alter_column(
        "diagnostic_reports",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("idx_diag_cuda"), table_name="diagnostic_reports")
    op.drop_index(op.f("idx_diag_os"), table_name="diagnostic_reports")
    op.drop_index(
        op.f("idx_profiles_os"),
        table_name="environment_profiles",
        postgresql_using="gin",
    )
    op.drop_index(op.f("idx_profiles_slug"), table_name="environment_profiles")
    op.drop_index(
        op.f("idx_profiles_tags"),
        table_name="environment_profiles",
        postgresql_using="gin",
    )
    op.drop_index(op.f("idx_generated_scripts_job_id"), table_name="generated_scripts")
    op.drop_index(
        op.f("idx_profile_packages_profile_id"), table_name="profile_packages"
    )
    op.drop_index(op.f("idx_jobs_profile_id"), table_name="script_generation_jobs")
    op.drop_index(op.f("idx_jobs_status"), table_name="script_generation_jobs")
    op.drop_constraint(
        op.f("script_generation_jobs_profile_id_fkey"),
        "script_generation_jobs",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "script_generation_jobs",
        "environment_profiles",
        ["profile_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "verification_checks",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "verification_results",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_constraint(
        op.f("verification_results_report_id_fkey"),
        "verification_results",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("verification_results_profile_id_fkey"),
        "verification_results",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "verification_results",
        "diagnostic_reports",
        ["report_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        None,
        "verification_results",
        "environment_profiles",
        ["profile_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "verification_results", type_="foreignkey")
    op.drop_constraint(None, "verification_results", type_="foreignkey")
    op.create_foreign_key(
        op.f("verification_results_profile_id_fkey"),
        "verification_results",
        "environment_profiles",
        ["profile_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("verification_results_report_id_fkey"),
        "verification_results",
        "diagnostic_reports",
        ["report_id"],
        ["id"],
    )
    op.alter_column(
        "verification_results",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "verification_checks",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_constraint(None, "script_generation_jobs", type_="foreignkey")
    op.create_foreign_key(
        op.f("script_generation_jobs_profile_id_fkey"),
        "script_generation_jobs",
        "environment_profiles",
        ["profile_id"],
        ["id"],
    )
    op.create_index(
        op.f("idx_jobs_status"), "script_generation_jobs", ["status"], unique=False
    )
    op.create_index(
        op.f("idx_jobs_profile_id"),
        "script_generation_jobs",
        ["profile_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_profile_packages_profile_id"),
        "profile_packages",
        ["profile_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_generated_scripts_job_id"),
        "generated_scripts",
        ["job_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_profiles_tags"),
        "environment_profiles",
        ["tags"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        op.f("idx_profiles_slug"), "environment_profiles", ["slug"], unique=False
    )
    op.create_index(
        op.f("idx_profiles_os"),
        "environment_profiles",
        ["os_support"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        op.f("idx_diag_os"), "diagnostic_reports", ["os_type"], unique=False
    )
    op.create_index(
        op.f("idx_diag_cuda"), "diagnostic_reports", ["cuda_version"], unique=False
    )
    op.alter_column(
        "diagnostic_reports",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.create_foreign_key(
        op.f("ai_suggestions_session_id_fkey"),
        "ai_suggestions",
        "ai_sessions",
        ["session_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "ai_suggestions",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "ai_sessions",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.create_foreign_key(
        op.f("ai_audit_log_session_id_fkey"),
        "ai_audit_log",
        "ai_sessions",
        ["session_id"],
        ["id"],
    )
    op.create_index(
        op.f("idx_audit_session"), "ai_audit_log", ["session_id"], unique=False
    )
    op.create_index(
        op.f("idx_audit_safety"), "ai_audit_log", ["safety_passed"], unique=False
    )
    op.alter_column(
        "ai_audit_log",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.create_table(
        "cuda_compatibility_matrix",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "cuda_version", sa.VARCHAR(length=16), autoincrement=False, nullable=False
        ),
        sa.Column(
            "min_driver_linux",
            sa.VARCHAR(length=32),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "min_driver_windows",
            sa.VARCHAR(length=32),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "cudnn_versions",
            postgresql.ARRAY(sa.VARCHAR()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "supported_archs",
            postgresql.ARRAY(sa.VARCHAR()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("notes", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("source_url", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("cuda_compatibility_matrix_pkey")),
        sa.UniqueConstraint(
            "cuda_version",
            name=op.f("cuda_compatibility_matrix_cuda_version_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    # ### end Alembic commands ###
