"""Add missing foreign keys ai session

Revision ID: f113b99acf31
Revises: a855f3a2d70d
Create Date: 2026-05-14 20:18:51.997506

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f113b99acf31"
down_revision: str | None = "a855f3a2d70d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        None, "ai_audit_log", "ai_sessions", ["session_id"], ["id"], ondelete="SET NULL"
    )
    op.create_foreign_key(
        None,
        "ai_sessions",
        "verification_results",
        ["verification_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        None,
        "ai_sessions",
        "environment_profiles",
        ["profile_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        None,
        "ai_sessions",
        "diagnostic_reports",
        ["diagnostic_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        None,
        "ai_suggestions",
        "ai_sessions",
        ["session_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "ai_suggestions", type_="foreignkey")
    op.drop_constraint(None, "ai_sessions", type_="foreignkey")
    op.drop_constraint(None, "ai_sessions", type_="foreignkey")
    op.drop_constraint(None, "ai_sessions", type_="foreignkey")
    op.drop_constraint(None, "ai_audit_log", type_="foreignkey")
    # ### end Alembic commands ###
