"""API-layer Pydantic schemas for AI troubleshoot and repair endpoints.

These schemas define the HTTP request/response contracts exposed by the
API. They are distinct from the internal AI models in ``app.ai.models``
to maintain a clean separation between API surface and internal logic.
"""

from typing import Any, Literal

from pydantic import BaseModel, Field

# ── Troubleshoot ──────────────────────────────────────────────────────────────


class TroubleshootRequestSchema(BaseModel):
    """POST /api/v1/troubleshoot — request body."""

    diagnostic: dict[str, Any] = Field(
        ...,
        description="Raw DiagnosticReport JSON from the CLI agent or frontend.",
    )
    profile_slug: str | None = Field(
        None,
        description="Target profile slug (e.g. 'pytorch-cuda').",
    )
    profile_name: str | None = Field(
        None,
        description="Human-readable profile name.",
    )
    target_os: str | None = Field(
        None,
        description="Target OS: LINUX, WSL, or WIN.",
    )
    python_version: str | None = Field(
        None,
        description="Requested Python version (e.g. '3.11').",
    )
    cuda_version: str | None = Field(
        None,
        description="Requested CUDA version (e.g. '12.1').",
    )
    user_description: str = Field(
        "",
        description="Free-text description of the issue from the user.",
        max_length=500,
    )


class SuggestedFixSchema(BaseModel):
    """A single AI-generated fix suggestion."""

    step: int
    title: str
    description: str
    severity: Literal["CRITICAL", "WARNING", "INFO"]
    safe_commands: list[str] = Field(default_factory=list)
    repair_template_id: str | None = None


class TroubleshootResponseSchema(BaseModel):
    """POST /api/v1/troubleshoot — response body."""

    session_id: str
    root_cause: str
    suggested_fixes: list[SuggestedFixSchema]
    repair_script_available: bool = False
    confidence: float = Field(0.0, ge=0.0, le=1.0)
    disclaimer: str = (
        "AI suggestions are advisory only. Review all steps before executing. "
        "EnvForge is not responsible for system changes."
    )


# ── Repair ────────────────────────────────────────────────────────────────────


class RepairRequestSchema(BaseModel):
    """POST /api/v1/repair — request body."""

    template_id: str = Field(
        ...,
        description="Repair template ID from AI suggestion.",
    )
    params: dict[str, Any] = Field(
        default_factory=dict,
        description="Template parameters (e.g. target_cuda_version).",
    )


class RepairResponseSchema(BaseModel):
    """POST /api/v1/repair — response body."""

    template_id: str
    filename: str
    content: str
    size_bytes: int
    disclaimer: str = (
        "This repair script was generated by EnvForge. "
        "Review it carefully before executing. "
        "EnvForge is not responsible for system changes."
    )


class RepairTemplateInfoSchema(BaseModel):
    """A single repair template description."""

    id: str
    description: str


class RepairTemplateListResponseSchema(BaseModel):
    """GET /api/v1/repair/templates — response body."""

    templates: list[RepairTemplateInfoSchema]


# ── Diagnose Explain ─────────────────────────────────────────────────────────


class DiagnoseExplainResponse(BaseModel):
    """POST /api/v1/diagnose/explain — response body.

    A plain-English explanation of what is wrong and what to do next,
    produced by the AI Troubleshooting Layer from a DiagnosticReport.
    """

    issue_summary: str = Field(
        ...,
        description="Plain-English explanation of what is wrong.",
    )
    root_cause: str = Field(
        ...,
        description="Root cause (e.g. 'CUDA version mismatch').",
    )
    suggested_steps: list[str] = Field(
        ...,
        description="Ordered remediation steps in plain English. No auto-execution.",
    )
    safe_to_auto_fix: bool = Field(
        False,
        description="Whether the fix can be mapped to an existing Jinja2 repair template.",
    )
    confidence: float = Field(
        0.0,
        ge=0.0,
        le=1.0,
        description="AI confidence in the diagnosis.",
    )
    disclaimer: str = Field(
        default="AI-generated advisory. Review all suggestions before executing.",
        description="Safety disclaimer.",
    )
